image: python:3.5
before_script:
    - printf "[settings]\nbrowser = firefox\nusername = kieranw\npassword = kieranw\nworkshop_site = stows" > ~/.reloaded.cfg
configs:
    script:
        python reloaded/configs.py

coverage:
    script:
        - coverage
