image: python:3.5
before_script:
    - apt-get install xvfb
    - pip install pyvirtualdisplay
    - printf "[settings]\nbrowser = firefox\nusername = kieranw\npassword = kieranw\nworkshop_site = stows" > ~/.reloaded.cfg
    - pip install nose
    - pip install pytest-cov
    - pip install selenium
    - cd /builds/k33k00/T-Reloaded
    - ls
configs:
    script:
        nosetests

cover:
    coverage: '/TOTAL *\d* *\d* *(\d*)%/'
    script:
        py.test --cov=reloaded
