image: python:3.5
before_script:
    - printf "[settings]\nbrowser = firefox\nusername = kieranw\npassword = kieranw\nworkshop_site = stows" > ~/.reloaded.cfg
    - pip install nose
    - pip install pytest-cov
    - cd /builds/k33k00/T-Reloaded
    - ls
configs:
    script:
        nosetests

cover:
    script:
        py.test --cov=reloaded
    coverage: '/\(d+.\d+\%\) covered/'
